[package]
name = "labels"
version = "0.1.1"
authors = ["JV <auburn.mutiny0e@icloud.com>"]
edition = "2021"

[dependencies]
gather = { version = "1.0.0", git = "https://github.com/exquisiteOntologist/gather" }

[profile.release]


[build]
target = "labels"

[[bin]]
name = "labels"
